#!/usr/bin/env bash
# Bash script that Install nginx on your web-01 server and requirements
sudo apt-get update -y
sudo apt-get install nginx -y
sudo sed -i 's/80 default_server/80/' /etc/nginx/sites-available/default
echo 'Hello World!' | sudo tee /var/www/html/index.html > /dev/nulg
service nginx restart
